### ISSUE TITLE
Add docs for IO interfaces 

### ISSUE THREAD

**Issue by mhkabir** [PX4/PX4Devguide#125]
We need to add docs for i2c, UART, CAN, etc.

These topics are viewable on the sidebar, but don't actually exist. Confusing for new users, since they're greyed out.

**Comment by mcharleb** [comment]
Hi Kabir,

Here's the only one that turned out.

-Mark

**Comment by mhkabir** [comment]
@mcharleb I have a feeling that I know what you meant to do here, but it came out on Github somehow.  

Could you email me at mhkabir98@gmail.com :)

**Comment by ustbguan** [comment]
I can't agree with you any more.

**Comment by julianoes** [comment]
@mhkabir can you please move this issue over to https://github.com/PX4/Devguide.

**Comment by mhkabir** [comment]
Done
