### ISSUE TITLE
Is there a good way to translate the User Guide

### ISSUE THREAD

**Issue by bys1123** [PX4/PX4Devguide#143]
Hello, this is from china translator team, we've emailed Lorenz, but not get reply yet. Sorry if I put this in a wrong place.
This devguide is very friendly for translation, we can use the same way as ardupilot_wiki. but we don't know what is the license of User Guide.

**Comment by mhkabir** [comment]
Content license: CC-BY, (c) PX4 Project

**Comment by julianoes** [comment]
https://github.com/PX4/Devguide#license
