### ISSUE TITLE
problems with debugger 

### ISSUE THREAD

**Issue by Userskii** [PX4/PX4Devguide#151]
Hi, I have just run the SITL simulantion using the command 
$ make posix_sitl_default gazebo_gdb
Howerer in the command line it said 

~/src/Firmware$ make posix_sitl_default gazebo_gdb
PX4 CONFIG: posix_sitl_default
make[1]: *** No rule to make target `gazebo_gdb'.  Stop.
make: *** [posix_sitl_default] Error 2

Do I miss something or do I have to modify some path? I can run a full simulation without debugger
 such as using $ make posix_sitl_default gazebo

Thanks.

**Comment by julianoes** [comment]
The correct semantic has 3 underscores.

`make posix_sitl_default gazebo___gdb`
