### ISSUE TITLE
Cant build PX4 filmware on snapdragon

### ISSUE THREAD

**Issue by mahesha-path** [PX4/PX4Devguide#177]
while running the command "  make eagle_default "  i faced these errors

anuj.gupta@CPU-291U:~/src/Firmware$ make eagle_default
PX4 CONFIG: /home/anuj.gupta/src/Firmware/build_posix_eagle_default
[  1%] [  1%] Built target git_gencpp
Built target git_genmsg
[  4%] Built target df_driver_framework
[  4%] Built target prebuild_targets
[  4%] [  5%] [  6%] Built target git_mavlink
Built target git_uavcan
Built target git_matrix
[  6%] Built target generate_px4muorb_stubs
[  7%] [  7%] Built target git_ecl
Built target git_jmavsim
[  7%] Built target git_gazebo
[  7%] Built target mixer_gen
[  8%] Built target xml_gen
[ 38%] Built target msg_gen
[ 39%] Built target generate_topic_listener
[ 39%] Built target platforms__common
[ 39%] [ 39%] Built target drivers__rgbled
Built target drivers__pwm_out_sim
[ 40%] [ 40%] Built target drivers__boards__sitl
Built target drivers__blinkm
[ 42%] Built target drivers__device
[ 43%] Built target drivers__qshell__posix
[ 44%] [ 45%] Built target drivers__led
[ 45%] Built target systemcmds__param
Built target systemcmds__mixer
[ 46%] Built target systemcmds__ver
[ 46%] Built target systemcmds__topic_listener
[ 46%] Built target modules__attitude_estimator_q
[ 47%] Built target modules__position_estimator_inav
[ 52%] Built target modules__mavlink
[ 53%] [ 53%] Built target modules__mc_pos_control
Built target modules__ekf2
[ 54%] Built target modules__mc_att_control
[ 57%] Built target modules__local_position_estimator
[ 57%] Built target modules__param
[ 59%] [ 60%] Built target modules__sensors
Built target modules__systemlib__mixer
[ 63%] Built target modules__uORB
[ 64%] Built target modules__sdlog2
[ 64%] Built target modules__dataman
[ 65%] Built target modules__muorb__krait
[ 69%] Built target modules__commander
[ 70%] [ 75%] Built target modules__simulator
Built target modules__navigator
[ 76%] Built target lib__controllib
[ 77%] Built target lib__mathlib
[ 77%] [ 77%] [ 77%] Built target lib__mathlib__math__filter
Built target lib__conversion
Built target lib__geo
[ 77%] [ 78%] Built target lib__geo_lookup
Built target lib__runway_takeoff
[ 78%] Built target lib__terrain_estimation
[ 78%] [ 85%] Built target lib__tailsitter_recovery
Built target lib__ecl
[ 88%] Built target platforms__posix__px4_layer
[ 88%] Built target lib__DriverFramework__framework
[ 88%] Built target modules__logger
[ 94%] Built target modules__systemlib
[ 98%] Built target platforms__posix__work_queue
Linking CXX executable px4
/home/anuj.gupta/Qualcomm/Hexagon_SDK/3.0/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find crt1.o: No such file or directory
/home/anuj.gupta/Qualcomm/Hexagon_SDK/3.0/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find crti.o: No such file or directory
/home/anuj.gupta/Qualcomm/Hexagon_SDK/3.0/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lpthread
/home/anuj.gupta/Qualcomm/Hexagon_SDK/3.0/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lrt
/home/anuj.gupta/Qualcomm/Hexagon_SDK/3.0/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lpthread
/home/anuj.gupta/Qualcomm/Hexagon_SDK/3.0/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.3/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lrt
collect2: error: ld returned 1 exit status
make[3]: *** [src/firmware/posix/px4] Error 1
make[2]: *** [src/firmware/posix/CMakeFiles/px4.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [posix_eagle_default] Error 2
   thanks

**Comment by mhkabir** [comment]
Please avoid creating duplicate issues across repositories for the same issue. 
Please refer to the issue in Firmware in the future.
