### ISSUE TITLE
npm install brings me " no such file or directory"

### ISSUE THREAD

**Issue by jiapei100** [PX4/PX4Devguide#178]
> jiapei:Devguide$ npm install
> npm WARN enoent ENOENT: no such file or directory, open '....../px4/Devguide/package.json'
> npm WARN Devguide No description
> npm WARN Devguide No repository field.
> npm WARN Devguide No README data
> npm WARN Devguide No license field.

**Comment by julianoes** [comment]
This repo is deprecated, the devguide has moved to https://github.com/PX4/Devguide/issues/.
Sorry about that.
