### ISSUE TITLE
Rendering it locally with correct styles

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/PX4Devguide#56]
@LorenzMeier 
Why does has Travis to copy the following style sheets? Can't we just put them there?

```
- cp theme/assets/style.css theme/assets/website/style.css
- cp theme/assets/print.css theme/assets/website/print.css
```

If I want to do the preview with the correct styles locally I also need to copy those.

**Comment by LorenzMeier** [comment]
Makes sense. Something is not quite right about the template.

**Comment by julianoes** [comment]
Closing, since it's moved to gitbook.
