### ISSUE TITLE
Update the template

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4Devguide#59]
A start would be to just link the search button to a google search containing: ```site:dev.px4.io```

**Comment by LorenzMeier** [comment]
Gitbook has it. Its just the 3DR template which is broken because of the local hackery. @kaitlynhova You must be running into the same issue with the 3DR dev guide - how did you resolve it?

**Comment by kaitlynhova** [comment]
Hey @LorenzMeier ! Actually,  I think Tim (tim@3drobotics.com) would be more familiar with this. I'll check in with him to see how he did it. Here is his [github profile](https://github.com/tcr3dr)

**Comment by julianoes** [comment]
@tcr3dr our search button is broken. Any advice how to get it back? Thanks.

**Comment by julianoes** [comment]
Bump! Anyone?

**Comment by julianoes** [comment]
Resolved with move to gitbook.
